### ISSUE TITLE
我下载了你的代码怎么运行

### ISSUE THREAD

**Issue by jiftle** [suziwen/markdownxiaoshujiang#129]
- 喜欢马克飞象的快捷键，怎么配置成马克飞象的快捷键。
  Ctrl + H，一次代表 ##
  Ctrl + H + H，  两次代表 ###
- windows7 操作系统，下如何运行你的工程。已经安装了node.js。

```
> node.js app.js
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:225:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
```
- 安装了express框架，执行指令仍然报错

```
$ npm install
npm WARN package.json markdown.xiaoshujiang@0.0.2 No license field.

> iconv@2.0.6 install E:\work\work_git\markdownxsj\node_modules\iconv
> node-gyp rebuild
...
c:\users\jiftle\.node-gyp\4.2.6\include\node\v8.h(3403): fatal error C1003: error count exceeds 100; stopping compilation [E:\work\work_git\markdownxsj\node_modules\jsdom\node_modules\contextify\build\contextify.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\work\work_git\markdownxsj\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.0.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

```

**Comment by suziwen** [comment]
目前快捷键生成的head标题只能是`===`,`---`格式，后续版本会改进。

github上的工程最好在linux系上运行。window下执行没有测试过，可能有些依赖需要自己解决。
