### ISSUE TITLE
8.10.0版本 绑定三方数据存储报错

### ISSUE THREAD

**Issue by squallsyttt** [suziwen/markdownxiaoshujiang#1653]
错误日志 和 截图如下
![小书匠报错截图](https://user-images.githubusercontent.com/29891953/184570905-c202eb10-348b-49c7-91fc-c2a539c61dc1.png)

2022-08-15T03:06:34.188Z - error: uncaughtException: parser.remove is not a function date=Mon Aug 15 2022 11:06:34 GMT+0800 (中国标准时间), pid=14240, uid=null, gid=null, cwd=C:\software\editor\Story, execPath=C:\software\editor\Story\Story-writer.exe, version=v18.7.0, argv=[C:\software\editor\Story\Story-writer.exe], rss=401956864, heapTotal=20713472, heapUsed=19432588, external=193302, arrayBuffers=0, loadavg=[0, 0, 0], uptime=9196, trace=[column=12, file=node:_http_common, function=freeParser, line=185, method=null, native=false, column=5, file=node:_http_client, function=TLSSocket.socketOnData, line=579, method=socketOnData, native=false, column=28, file=node:events, function=TLSSocket.emit, line=513, method=emit, native=false, column=12, file=node:internal/streams/readable, function=addChunk, line=324, method=null, native=false, column=9, file=node:internal/streams/readable, function=readableAddChunk, line=297, method=null, native=false, column=10, file=node:internal/streams/readable, function=Readable.push, line=234, method=push, native=false, column=23, file=node:internal/stream_base_commons, function=TLSWrap.onStreamRead, line=190, method=onStreamRead, native=false], stack=[TypeError: parser.remove is not a function,     at freeParser (node:_http_common:185:12),     at TLSSocket.socketOnData (node:_http_client:579:5),     at TLSSocket.emit (node:events:513:28),     at addChunk (node:internal/streams/readable:324:12),     at readableAddChunk (node:internal/streams/readable:297:9),     at Readable.push (node:internal/streams/readable:234:10),     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)]
2022-08-15T03:06:34.194Z - error: uncaughtException: MemBuffer overrun date=Mon Aug 15 2022 11:06:34 GMT+0800 (中国标准时间), pid=14240, uid=null, gid=null, cwd=C:\software\editor\Story, execPath=C:\software\editor\Story\Story-writer.exe, version=v18.7.0, argv=[C:\software\editor\Story\Story-writer.exe], rss=401903616, heapTotal=21499904, heapUsed=19025012, external=155405, arrayBuffers=0, loadavg=[0, 0, 0], uptime=9196, trace=[column=55, file=C:\software\editor\Story\node_modules\evernote\lib\thrift\transport\memBuffer.js, function=MemBuffer.read, line=29, method=read, native=false, column=38, file=C:\software\editor\Story\node_modules\evernote\lib\thrift\protocol\binaryProtocol.js, function=BinaryProtocol.readMessageBegin, line=203, method=readMessageBegin, native=false, column=27, file=C:\software\editor\Story\node_modules\evernote\lib\thrift\thrift.js, function=Thrift.Method.processResponse, line=184, method=processResponse, native=false, column=42, file=C:\software\editor\Story\node_modules\evernote\lib\thrift\thrift.js, function=null, line=165, method=null, native=false, column=20, file=C:\software\editor\Story\node_modules\evernote\lib\thrift\protocol\binaryProtocol.js, function=wrapTransport, line=48, method=null, native=false, column=27, file=C:\software\editor\Story\node_modules\evernote\lib\thrift\transport\binaryHttpTransport.js, function=null, line=87, method=null, native=false, column=35, file=node:events, function=IncomingMessage.emit, line=525, method=emit, native=false, column=12, file=node:internal/streams/readable, function=endReadableNT, line=1359, method=null, native=false, column=21, file=node:internal/process/task_queues, function=process.processTicksAndRejections, line=82, method=processTicksAndRejections, native=false], stack=[Error: MemBuffer overrun,     at MemBuffer.read (C:\software\editor\Story\node_modules\evernote\lib\thrift\transport\memBuffer.js:29:55),     at BinaryProtocol.readMessageBegin (C:\software\editor\Story\node_modules\evernote\lib\thrift\protocol\binaryProtocol.js:203:38),     at Thrift.Method.processResponse (C:\software\editor\Story\node_modules\evernote\lib\thrift\thrift.js:184:27),     at Thrift.Method.<anonymous> (C:\software\editor\Story\node_modules\evernote\lib\thrift\thrift.js:165:42),     at wrapTransport (C:\software\editor\Story\node_modules\evernote\lib\thrift\protocol\binaryProtocol.js:48:20),     at IncomingMessage.<anonymous> (C:\software\editor\Story\node_modules\evernote\lib\thrift\transport\binaryHttpTransport.js:87:27),     at IncomingMessage.emit (node:events:525:35),     at endReadableNT (node:internal/streams/readable:1359:12),     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
2022-08-15T03:06:34.198Z - error: uncaughtException: parser.remove is not a function date=Mon Aug 15 2022 11:06:34 GMT+0800 (中国标准时间), pid=14240, uid=null, gid=null, cwd=C:\software\editor\Story, execPath=C:\software\editor\Story\Story-writer.exe, version=v18.7.0, argv=[C:\software\editor\Story\Story-writer.exe], rss=402006016, heapTotal=21499904, heapUsed=19094348, external=155405, arrayBuffers=0, loadavg=[0, 0, 0], uptime=9196, trace=[column=12, file=node:_http_common, function=freeParser, line=185, method=null, native=false, column=5, file=node:_http_client, function=TLSSocket.socketCloseListener, line=468, method=socketCloseListener, native=false, column=35, file=node:events, function=TLSSocket.emit, line=525, method=emit, native=false, column=14, file=node:net, function=null, line=757, method=null, native=false, column=7, file=node:_tls_wrap, function=TCP.done, line=583, method=done, native=false], stack=[TypeError: parser.remove is not a function,     at freeParser (node:_http_common:185:12),     at TLSSocket.socketCloseListener (node:_http_client:468:5),     at TLSSocket.emit (node:events:525:35),     at node:net:757:14,     at TCP.done (node:_tls_wrap:583:7)]

**Comment by suziwen** [comment]
确实有问题，一会发布个新客户端版本。

**Comment by suziwen** [comment]
更新到 `8.10.1`
