### ISSUE TITLE
更新后 数据同步出问题了

### ISSUE THREAD

**Issue by canghaiwuhen** [suziwen/markdownxiaoshujiang#1674]
今天更新到最新版

之前正常是使用的数据同步出了问题。。。

点测试，或者全库同步，卡在数据准备，然后后面就失败了

![image](https://user-images.githubusercontent.com/4746188/204087056-eaef2dce-0e2b-45ca-a466-7741fbe3c9a3.png)

**Comment by canghaiwuhen** [comment]
2022-10-29T04:45:37.369Z - error: uncaughtException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/pouchdb/worker/async.js' failed to load. date=Sat Oct 29 2022 12:45:37 GMT+0800 (中国标准时间), pid=20716, uid=null, gid=null, cwd=D:\Edit\Story, execPath=D:\Edit\Story\Story-writer.exe, version=v18.7.0, argv=[D:\Edit\Story\Story-writer.exe], rss=354570240, heapTotal=19402752, heapUsed=18059520, external=475744, arrayBuffers=0, loadavg=[0, 0, 0], uptime=4072, trace=[column=11078, file=chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js, function=d, line=1, method=null, native=false, column=13469, file=chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js, function=D, line=1, method=null, native=false, column=15308, file=chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js, function=null, line=1, method=null, native=false], stack=[Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/pouchdb/worker/async.js' failed to load.,     at d (chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js:1:11078),     at D (chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js:1:13469),     at chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js:1:15308]

**Comment by suziwen** [comment]
感觉像是你的数据库服务器没办法访问了，看一下是不是数据库地址写错了，或者到浏览器里，访问一下你的数据库地址，看返回了什么数据？

**Comment by canghaiwuhen** [comment]
> 感觉像是你的数据库服务器没办法访问了，看一下是不是数据库地址写错了，或者到浏览器里，访问一下你的数据库地址，看返回了什么数据？

没错的，浏览器直接访问返回是账密不对
{"error":"unauthorized","reason":"You are not authorized to access this db."}
账密有输入

**Comment by canghaiwuhen** [comment]
![image](https://user-images.githubusercontent.com/4746188/204094605-218ae9c2-7630-49a9-8dd7-cfef5b839db3.png)

**Comment by canghaiwuhen** [comment]
带上账密
![image](https://user-images.githubusercontent.com/4746188/204094657-a5133db5-86c9-49e5-a9fb-8072210db8d2.png)

**Comment by canghaiwuhen** [comment]
8.4.1老版本，同样配置，同样的数据库
![image](https://user-images.githubusercontent.com/4746188/204095161-6a8d03fe-3a77-450a-b97d-792a072542b6.png)

**Comment by canghaiwuhen** [comment]
像是bug，一台pc上8.4.1老版本升级到最新的没问题，但另一台升级的就有我发的这个问题，同样的配置

**Comment by canghaiwuhen** [comment]
有问题的这个，重装软件也不行

**Comment by canghaiwuhen** [comment]
删除AppData\Local\storywriter整个目录，然后重新登录同步数据正常了，应该是一个bug

**Comment by suziwen** [comment]
还是感觉像是网络问题，或者有什么防火墙限制了访问．

你试一下到`小书匠>设置>网络` 里，测试一下数据库服务器是否可以访问.

代理服务器和端口都留空，然后在测试地址里写上你的数据库服务器的根地址（或者是一个不需要认证的地址，比如 http://localhost:5984）

![image](https://user-images.githubusercontent.com/57370/204096130-de7b12cd-4979-4409-bb2f-36bc957a2352.png)

**Comment by suziwen** [comment]
嗯，也有可能是你说的 bug , 看看后面有没有其他用户有类似的情况，因为我这边没办法重现，不好找出具体原因．

**Comment by canghaiwuhen** [comment]
> 还是感觉像是网络问题，或者有什么防火墙限制了访问．
> 
> 你试一下到`小书匠>设置>网络` 里，测试一下数据库服务器是否可以访问.
> 
> 代理服务器和端口都留空，然后在测试地址里写上你的数据库服务器的根地址（或者是一个不需要认证的地址，比如 [http://localhost:5984）](http://localhost:5984%EF%BC%89)
> 
> ![image](https://user-images.githubusercontent.com/57370/204096130-de7b12cd-4979-4409-bb2f-36bc957a2352.png)

防火墙没有限制，而且之前都用的好好的，就升级后挂了，现在已经恢复了，确实不好复现，看以后还会不会出现吧，可能就是偶发的bug。
