### ISSUE TITLE
Windows版本鼠标滑动经过https等链接提示：出现异常: {"isTrusted":true}

### ISSUE THREAD

**Issue by SiDaiJie** [suziwen/markdownxiaoshujiang#1724]
![image](https://github.com/suziwen/markdownxiaoshujiang/assets/71361064/58af866e-f54f-4cde-86b5-c04dd810dd59)

**Comment by suziwen** [comment]
像是数据库所在的盘空间不够了，或者是数据库坏了。

可以到 `小书匠主按钮>关于` 界面里，打开数据文件所在路径的文件夹，临时把该文件夹移走，再重启小书匠看看。

移走前建议把整个文件夹先备份下，也可以到 `小书匠主按钮>数据>基本` 里，备份数据库。


![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/64fb48eb-8bac-445c-9b72-2aae85f2fea7)

**Comment by SiDaiJie** [comment]
## 我发现触发原因可能是别的原因

 - 在这里点击链接是不会触发错误的

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/71361064/27cdf685-8068-4f2f-b0b0-e3f981aa4f89)

 - 在操作红色框的链接的时候会提示异常，在操作绿色那个框之后没出现异常

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/71361064/9e69451d-a06a-4ca6-b2fe-faa2e75f643c)

 - 这个的报错我没能在stroy_exceptions.log中看到日志，我打开这个日志文件里面有且只有这么一行Error
 
2024-04-02T08:18:43.985Z - error: uncaughtException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/pouchdb/worker/pouchdb.indexeddb.js' failed to load. date=Tue Apr 02 2024 16:18:43 GMT+0800 (中国标准时间), pid=45240, uid=null, gid=null, cwd=D:\ProgramFiles\StoryEditor, execPath=D:\ProgramFiles\StoryEditor\Story-writer.exe, version=v18.7.0, argv=[D:\ProgramFiles\StoryEditor\Story-writer.exe], rss=192540672, heapTotal=19927040, heapUsed=18102748, external=441547, arrayBuffers=0, loadavg=[0, 0, 0], uptime=1315723, trace=[column=11839, file=chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js, function=g, line=1, method=null, native=false, column=14285, file=chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js, function=I, line=1, method=null, native=false, column=16169, file=chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js, function=null, line=1, method=null, native=false], stack=[Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/pouchdb/worker/pouchdb.indexeddb.js' failed to load.,     at g (chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js:1:11839),     at I (chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js:1:14285),     at chrome-extension://jalbgaejjmdihbhmdepjgcdikbeclnbe/app/js/client_worker.js:1:16169]

**Comment by suziwen** [comment]
那比较奇怪了，是不是这篇文章内容有什么特殊的符号或者文字引起的？

你试下用 chrome 浏览器的隐身模式访问小书匠网页版 https://markdown.xiaoshujiang.com , 新建一篇文章，再把相应的内容粘贴过去，看下是否也会有问题？

**Comment by SiDaiJie** [comment]
访问小书匠网页版，把相应的内容粘贴过去没有问题；

**Comment by suziwen** [comment]
那你试下用下面的命令启动小书匠，把数据目录切换到非系统盘上(比如 D 盘的 tempdata 文件夹下)，看看还会出现这种情况吗？

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/d09ddcda-9d9f-4b99-9cf4-cda1f45562ef)



``` 
--user-data-dir=d:\tempdata
```

``` 
2021/11/30  00:51           164,747 v8_context_snapshot.bin
2021/11/30  00:51         3,881,472 vk_swiftshader.dll
2021/11/30  00:51               106 vk_swiftshader_icd.json
2021/11/30  00:51           685,056 vulkan-1.dll
              24 个文件    244,600,653 字节
               7 个目录 23,563,378,688 可用字节

C:\Program Files\Story>Story-writer.exe --user-data-dir=d:\tempdata

C:\Program Files\Story>
```

**Comment by SiDaiJie** [comment]
- 问题还是存在，左右两边鼠标过去都会弹出异常的框

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/71361064/49df2ec0-4015-4295-9429-d53c06120fd2)

**Comment by suziwen** [comment]
那能把这个 markdown 文件发到我邮箱吗?  suziwen1@gmail.com

**Comment by SiDaiJie** [comment]
好的，已发送到邮箱

**Comment by suziwen** [comment]
测试你发的 md 文件,我这边客户端打开没问题.....

能把数据目录压缩成 zip 发过来看下吗？也就是 `d:\tempdata`  这个目录。
