### ISSUE TITLE
小书匠运行不了了

### ISSUE THREAD

**Issue by zozo825117** [suziwen/markdownxiaoshujiang#665]
没做什么操作，运行不了了，卸载了重装最新的版本还是一样，只在任务管理器里面有三个进程，然后就没有了，求解。

**Comment by zozo825117** [comment]
···
[0103/152838.212:ERROR:http_transport_win.cc(127)] WinHttpCrackUrl: URL 未使用可识别的协议  (0x2ee6)
[0103/152850.642:ERROR:registration_protocol_win.cc(55)] CreateFile: 系统找不到指定的文件。 (0x2)
[0103/153603.119:WARNING:process_subrange_reader.cc(59)] range 0x140108000 + 0x48af8 (64) outside of  range 0x140000000 + 0x114000 (64) for D:\Program Files\Story\Story-writer.exe resources
[0103/153603.176:ERROR:http_transport_win.cc(127)] WinHttpCrackUrl: URL 未使用可识别的协议  (0x2ee6)
···

**Comment by zozo825117** [comment]
https://github.com/nwjs/nw.js/issues/6163
好像是个挺麻烦的问题，改用网页版算了，发现网页版挺流畅的么，还支持有道云。
就是小书匠的账号怎么登陆不了了？

**Comment by suziwen** [comment]
嗯，感觉和你的操作系统环境关系比较大。


-------------------

登陆不了？报什么错误没。我这边登陆没有问题。

**Comment by zozo825117** [comment]
是网页版登陆的时候   错误是
>**提交出错:login failed**

重置密码，发过来的链接，点开又是提示 ：
> 401 Invalid Access Token
code: INVALID_TOKEN

**Comment by zozo825117** [comment]
体验不是很好啊

**Comment by suziwen** [comment]
好了，再重新发一封重置密码的邮件就可以了。

**Comment by zozo825117** [comment]
恩，可以了。

**Comment by zozo825117** [comment]
知道是什么原因了，今天在运行 android studio的时候，一直出现这样的错误，感觉应该是网络问题，google了一下，http://forum.cocos.com/t/cocos2dx3-16-android-studio2-3-3-android-gradle/54281
**netsh winsock reset**不用重启，就都搞定了。
```
23:38:46.722 [ERROR] [system.err] FAILURE: Build failed with an exception.
23:38:46.722 [ERROR] [system.err] 
23:38:46.722 [ERROR] [system.err] * What went wrong:
23:38:46.722 [ERROR] [system.err] java.net.SocketException: Bad address: Cannot bind
23:38:46.722 [ERROR] [system.err] 
23:38:46.722 [ERROR] [system.err] * Try:
23:38:46.723 [ERROR] [system.err] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
23:38:46.724 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Removing daemon address: [bb1dcd2b-483b-4c5d-a97c-54a5d9081ac6 port:54335, addresses:[/127.0.0.1]]
23:38:46.725 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] VM shutdown hook was unable to remove the daemon address from the registry. It will be cleaned up later.
org.gradle.api.UncheckedIOException: java.net.SocketException: Bad address: Cannot bind
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
	at org.gradle.cache.internal.FileLockCommunicator.<init>(FileLockCommunicator.java:40)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.getCommunicator(DefaultFileLockContentionHandler.java:153)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.reservePort(DefaultFileLockContentionHandler.java:145)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:85)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:73)
	at org.gradle.cache.internal.OnDemandFileAccess.updateFile(OnDemandFileAccess.java:45)
	at org.gradle.cache.internal.SimpleStateCache.update(SimpleStateCache.java:63)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.update(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:43)
	at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.remove(PersistentDaemonRegistry.java:127)
	at org.gradle.launcher.daemon.server.Daemon$1.run(Daemon.java:128)
	at org.gradle.process.internal.shutdown.ShutdownHookActionRegister$GradleShutdownHook.run(ShutdownHookActionRegister.java:41)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Bad address: Cannot bind
	at java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.bind0(DualStackPlainDatagramSocketImpl.java:84)
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)
	at java.net.DatagramSocket.bind(DatagramSocket.java:392)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
	at org.gradle.cache.internal.FileLockCommunicator.<init>(FileLockCommunicator.java:38)
```
